---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 07/02/24 18:12
---

---@class MousePrey

local MousePrey = {}

local bait = require("Bait_TS")
local trap = require("Trap_TS")
local zone = require("Zone_TS")

local debugDiagnostics = require("lib/DebugDiagnostics")

---@type int
local multiplierPrey

---@type int
local multiplierPreySize

local choicesPreys = {}

local function bait_TDD()
    --                  ** BAIT **
    ---@type int
    local expectedValueCheese = 60 * multiplierPrey
    ---@type int
    local expectedValueChocolate = 30 * multiplierPrey
    ---@type int
    local expectedValuePeanutButter = 40 * multiplierPrey
    ---@type int
    local expectedValueProcessedCheese = 55 * multiplierPrey
    ---@type int
    local expectedValueTomato = 35 * multiplierPrey

    ---@type int
    local currentValueCheese = choicesPreys.baits[bait.bait.CHEESE]
    ---@type int
    local currentValueChocolate = choicesPreys.baits[bait.bait.CHOCOLATE]
    ---@type int
    local currentValuePeanutButter = choicesPreys.baits[bait.bait.PEANUT_BUTTER]
    ---@type int
    local currentValueProcessedCheese = choicesPreys.baits[bait.bait.PROCESSED_CHEESE]
    ---@type int
    local currentValueTomato = choicesPreys.baits[bait.bait.TOMATO]

    debugDiagnostics.checkTest(expectedValueCheese, currentValueCheese, "Mouse bait " .. bait.bait.CHEESE)
    debugDiagnostics.checkTest(expectedValueChocolate, currentValueChocolate, "Mouse bait " .. bait.bait.CHOCOLATE)
    debugDiagnostics.checkTest(expectedValuePeanutButter, currentValuePeanutButter, "Mouse bait " .. bait.bait.PEANUT_BUTTER)
    debugDiagnostics.checkTest(expectedValueProcessedCheese, currentValueProcessedCheese, "Mouse bait " .. bait.bait.PROCESSED_CHEESE)
    debugDiagnostics.checkTest(expectedValueTomato, currentValueTomato, "Mouse bait " .. bait.bait.TOMATO)
end

local function zone_TDD()
    ---@type int
    local expectedDeepForest = 10 * multiplierPrey
    ---@type int
    local expectedForest = 10 * multiplierPrey
    ---@type int
    local expectedTownZone = 50 * multiplierPrey
    ---@type int
    local expectedTrailerPark = 60 * multiplierPrey
    ---@type int
    local expectedVegetation = 20 * multiplierPrey

    ---@type int
    local currentValueDeepForest = choicesPreys.zone[zone.zone.DEEP_FOREST]
    ---@type int
    local currentValueForest = choicesPreys.zone[zone.zone.FOREST]
    ---@type int
    local currentValueTownZone = choicesPreys.zone[zone.zone.TOWN_ZONE]
    ---@type int
    local currentValueTrailerPark = choicesPreys.zone[zone.zone.TRAILER_PARK]
    ---@type int
    local currentValueVegetation = choicesPreys.zone[zone.zone.VEGETATION]

    debugDiagnostics.checkTest(expectedDeepForest, currentValueDeepForest, "Mouse zone - " .. zone.zone.DEEP_FOREST)
    debugDiagnostics.checkTest(expectedForest, currentValueForest, "Mouse zone - " .. zone.zone.FOREST)
    debugDiagnostics.checkTest(expectedTownZone, currentValueTownZone, "Mouse zone - " .. zone.zone.TOWN_ZONE)
    debugDiagnostics.checkTest(expectedTrailerPark, currentValueTrailerPark, "Mouse zone - " .. zone.zone.TRAILER_PARK)
    debugDiagnostics.checkTest(expectedVegetation, currentValueVegetation, "Mouse zone - " .. zone.zone.VEGETATION)

end

local function multiplierPreySize_TDD()
    ---@type int
    local minSizePrey = 1
    ---@type int
    local maxSizePrey = 10

    ---@type int
    local expectedMinSize = minSizePrey * multiplierPreySize
    ---@type int
    local expectedMaxSize = maxSizePrey * multiplierPreySize

    ---@type int
    local currentMinSize = choicesPreys.minSize
    ---@type int
    local currentMaxSize = choicesPreys.maxSize

    debugDiagnostics.checkTest(expectedMinSize, currentMinSize, "Mouse size min")
    debugDiagnostics.checkTest(expectedMaxSize, currentMaxSize, "Mouse size max")
end

local function trap_TDD()
    ---@type int
    local expectedTrapMouse = 30 * multiplierPrey

    ---@type int
    local currentTrapMouse = choicesPreys.traps[trap.trap.MOUSE]

    debugDiagnostics.checkTest(expectedTrapMouse, currentTrapMouse, "Mouse trap - " .. trap.trap.MOUSE)
end

local function choicesPrey(prey)
    for i, v in pairs(Animals) do
        if v.type == prey then
            choicesPreys = v
            break
        end
    end
end

function MousePrey.init()
    multiplierPrey = SandboxVars.TrappingSurvival.Mouse
    multiplierPreySize = SandboxVars.TrappingSurvival.MouseSize

    choicesPrey("mouse")

    bait_TDD()
    zone_TDD()
    trap_TDD()
    multiplierPreySize_TDD()

end

return MousePrey
