---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 10/02/24 10:10
---

---@class SquirrelPrey

local SquirrelPrey = {}

local bait = require("Bait_TS")
local trap = require("Trap_TS")
local zone = require("Zone_TS")

local debugDiagnostics = require("lib/DebugDiagnostics")

---@type int
local multiplierPrey

---@type int
local multiplierPreySize

local choicesPreys = {}

local function bait_TDD()
    --                  ** BAIT **
    ---@type int
    local expectedValueApple = 40 * multiplierPrey
    ---@type int
    local expectedValueBellPepper = 30 * multiplierPrey
    ---@type int
    local expectedValueCereal = 45 * multiplierPrey
    ---@type int
    local expectedValueCorn = 40 * multiplierPrey
    ---@type int
    local expectedValueOrange = 40 * multiplierPrey
    ---@type int
    local expectedValueLettuce = 40 * multiplierPrey
    ---@type int
    local expectedValuePeach = 35 * multiplierPrey
    ---@type int
    local expectedValuePeanutButter = 45 * multiplierPrey
    ---@type int
    local expectedValuePeanuts = 40 * multiplierPrey
    ---@type int
    local expectedValuePopcorn = 40 * multiplierPrey

    ---@type int
    local currentValueApple = choicesPreys.baits[bait.bait.APPLE]
    ---@type int
    local currentValueBellPepper = choicesPreys.baits[bait.bait.BELL_PEPPER]
    ---@type int
    local currentValueCereal = choicesPreys.baits[bait.bait.CEREAL]
    ---@type int
    local currentValueCorn = choicesPreys.baits[bait.bait.CORN]
    ---@type int
    local currentValueOrange = choicesPreys.baits[bait.bait.ORANGE]
    ---@type int
    local currentValueLettuce = choicesPreys.baits[bait.bait.LETTUCE]
    ---@type int
    local currentValuePeach = choicesPreys.baits[bait.bait.PEACH]
    ---@type int
    local currentValuePeanutButter = choicesPreys.baits[bait.bait.PEANUT_BUTTER]
    ---@type int
    local currentValuePeanuts = choicesPreys.baits[bait.bait.PEANUTS]
    ---@type int
    local currentValuePopcorn = choicesPreys.baits[bait.bait.POPCORN]

    debugDiagnostics.checkTest(expectedValueApple, currentValueApple, "Squirrel bait - " .. bait.bait.APPLE)
    debugDiagnostics.checkTest(expectedValueBellPepper, currentValueBellPepper, "Squirrel bait - " .. bait.bait.BELL_PEPPER)
    debugDiagnostics.checkTest(expectedValueCereal, currentValueCereal, "Squirrel bait - " .. bait.bait.CEREAL)
    debugDiagnostics.checkTest(expectedValueCorn, currentValueCorn, "Squirrel bait - " .. bait.bait.CORN)
    debugDiagnostics.checkTest(expectedValueOrange, currentValueOrange, "Squirrel bait - " .. bait.bait.ORANGE)
    debugDiagnostics.checkTest(expectedValueLettuce, currentValueLettuce, "Squirrel bait - " .. bait.bait.LETTUCE)
    debugDiagnostics.checkTest(expectedValuePeach, currentValuePeach, "Squirrel bait - " .. bait.bait.PEACH)
    debugDiagnostics.checkTest(expectedValuePeanutButter, currentValuePeanutButter, "Squirrel bait - " .. bait.bait.PEANUT_BUTTER)
    debugDiagnostics.checkTest(expectedValuePeanuts, currentValuePeanuts, "Squirrel bait - " .. bait.bait.PEANUTS)
    debugDiagnostics.checkTest(expectedValuePopcorn, currentValuePopcorn, "Squirrel bait - " .. bait.bait.POPCORN)
end

local function zone_TDD()
    --                  ** ZONE **
    ---@type int
    local expectedDeepForest = 15 * multiplierPrey
    ---@type int
    local expectedForest = 12 * multiplierPrey
    ---@type int
    local expectedTownZone = 2 * multiplierPrey
    ---@type int
    local expectedTrailerPark = 2 * multiplierPrey
    ---@type int
    local expectedVegetation = 10 * multiplierPrey

    ---@type int
    local currentValueDeepForest = choicesPreys.zone[zone.zone.DEEP_FOREST]
    ---@type int
    local currentValueForest = choicesPreys.zone[zone.zone.FOREST]
    ---@type int
    local currentValueTownZone = choicesPreys.zone[zone.zone.TOWN_ZONE]
    ---@type int
    local currentValueTrailerPark = choicesPreys.zone[zone.zone.TRAILER_PARK]
    ---@type int
    local currentValueVegetation = choicesPreys.zone[zone.zone.VEGETATION]

    debugDiagnostics.checkTest(expectedDeepForest, currentValueDeepForest, "Squirrel zone - " .. zone.zone.DEEP_FOREST)
    debugDiagnostics.checkTest(expectedForest, currentValueForest, "Squirrel zone - " .. zone.zone.FOREST)
    debugDiagnostics.checkTest(expectedTownZone, currentValueTownZone, "Squirrel zone - " .. zone.zone.TOWN_ZONE)
    debugDiagnostics.checkTest(expectedTrailerPark, currentValueTrailerPark, "Squirrel zone - " .. zone.zone.TRAILER_PARK)
    debugDiagnostics.checkTest(expectedVegetation, currentValueVegetation, "Squirrel zone - " .. zone.zone.VEGETATION)
end

local function trap_TDD()
    --                  ** TRAP **
    ---@type int
    local expectedValueBox = 25 * multiplierPrey
    ---@type int
    local expectedValueCage = 40 * multiplierPrey
    ---@type int
    local expectedValueCrate = 30 * multiplierPrey
    ---@type int
    local expectedValueSnare = 30 * multiplierPrey

    ---@type int
    local currentValueBox = choicesPreys.traps[trap.trap.BOX]
    ---@type int
    local currentValueCage = choicesPreys.traps[trap.trap.CAGE]
    ---@type int
    local currentValueCrate = choicesPreys.traps[trap.trap.CRATE]
    ---@type int
    local currentValueSnare = choicesPreys.traps[trap.trap.SNARE]

    debugDiagnostics.checkTest(expectedValueBox, currentValueBox, "Squirrel trap - " .. trap.trap.BOX)
    debugDiagnostics.checkTest(expectedValueCage, currentValueCage, "Squirrel trap - " .. trap.trap.CAGE)
    debugDiagnostics.checkTest(expectedValueCrate, currentValueCrate, "Squirrel trap - " .. trap.trap.CRATE)
    debugDiagnostics.checkTest(expectedValueSnare, currentValueSnare, "Squirrel trap - " .. trap.trap.SNARE)
end

local function multiplierPreySize_TDD()
    ---@type int
    local minSizePrey = 30
    ---@type int
    local maxSizePrey = 100

    ---@type int
    local expectedMinSize = minSizePrey * multiplierPreySize
    ---@type int
    local expectedMaxSize = maxSizePrey * multiplierPreySize

    ---@type int
    local currentMinSize = choicesPreys.minSize
    ---@type int
    local currentMaxSize = choicesPreys.maxSize

    debugDiagnostics.checkTest(expectedMinSize, currentMinSize, "Squirrel minSize")
    debugDiagnostics.checkTest(expectedMaxSize, currentMaxSize, "Squirrel maxSize")
end

local function choicesPrey(prey)
    for i, v in pairs(Animals) do
        if v.type == prey then
            choicesPreys = v
            break
        end
    end
end

function SquirrelPrey.init()
    multiplierPrey = SandboxVars.TrappingSurvival.Squirrel
    multiplierPreySize = SandboxVars.TrappingSurvival.SquirrelSize

    choicesPrey("squirrel")

    bait_TDD()
    zone_TDD()
    trap_TDD()
    multiplierPreySize_TDD()
end

return SquirrelPrey
