---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 26/04/23 17:41
---
require("server/TrappingSurvival")
--require("debug/BirdPrey_TDD")
local birdPrey_TDD = require("debug/BirdPrey_TDD")
local mousePrey_TDD = require("debug/MousePrey_TDD")
local rabbitPrey_TDD = require("debug/RabbitPrey_TDD")
local ratPrey_TDD = require("debug/RatPrey_TDD")
local squirrelPrey_TDD = require("debug/SquirrelPrey_TDD")

local debugDiagnostics = require("lib/DebugDiagnostics")


local function checkSandBox()
    --- **Check SandboxVars 1 is default value**
    ---@type int
    local expectedDefaultValue = 1
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.Bird, "SandBox - Bird" )
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.BirdSize, "SandBox - Bird Size" )
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.Mouse, "SandBox - Mouse" )
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.MouseSize, "SandBox - Mouse Size" )
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.Rabbit, "SandBox - Rabbit" )
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.RabbitSize, "SandBox - Rabbit Size" )
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.Rat, "SandBox - Rat" )
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.RatSize, "SandBox - Rat Size" )
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.Squirrel, "SandBox - Squirrel" )
    debugDiagnostics.checkTest(expectedDefaultValue, SandboxVars.TrappingSurvival.SquirrelSize, "SandBox - Squirrel Size" )
end

local function setSandBox()
    SandboxVars.TrappingSurvival.Bird = 0.9
    SandboxVars.TrappingSurvival.BirdSize = 0.9
    SandboxVars.TrappingSurvival.Mouse = 0.9
    SandboxVars.TrappingSurvival.MouseSize = 0.9
    SandboxVars.TrappingSurvival.Rabbit = 0.9
    SandboxVars.TrappingSurvival.RabbitSize = 0.9
    SandboxVars.TrappingSurvival.Rat = 0.9
    SandboxVars.TrappingSurvival.RatSize = 0.9
    SandboxVars.TrappingSurvival.Squirrel = 0.9
    SandboxVars.TrappingSurvival.SquirrelSize = 0.9
end

---@param character IsoGameCharacter
local function key82(character, key)
    if key == 82 then -- <<<< numpad 0
        print("Key = numpad 0 > init Test \n")
        debugDiagnostics.setVerbose(false)

        checkSandBox()
        setSandBox()

        initTrappingSurvival()

        birdPrey_TDD.init()
        mousePrey_TDD.init()
        rabbitPrey_TDD.init()
        ratPrey_TDD.init()
        squirrelPrey_TDD.init()

    debugDiagnostics.displayTest()
    end
end

---@param character IsoGameCharacter
local function key73(character, key)
    if key == 73 then -- <<<< numpad 9
        print("Key = numpad 9 > Kill charater \n")
        character:die()
    end
end

local function onCustomUIKeyPressed(key)
    local character = getPlayer()

    key82(character, key) -- numpad 0
    key73(character, key) -- numpad 9
end

Events.OnCustomUIKeyPressed.Add(onCustomUIKeyPressed)
