---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/08/23 23:14
---

-- https://pzwiki.net/wiki/Trapping
-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

---@class Mouse

local creatureFactory = require("CreatureFactory")
local dataValidator = require("lib/DataValidator")
local errHandler = require("lib/ErrHandler")

---@type table
local mouse = {}

local trap = require("Trap")
local bait = require("Bait")
local zone = require("Zone")

--- ---------------------- Start Mouse Default values -------------------------------

--                  ** BAIT **
---@type int
local cheese = 60
---@type int
local chocolate = 30
---@type int
local peanutButter = 40
---@type int
local processedCheese = 55
---@type int
local tomato = 35

--                  ** ZONE **
---@type int
local deepForest = 10
---@type int
local farmLand = 60
---@type int
local forest = 10
---@type int
local townZone = 50
---@type int
local trailerPark = 60
---@type int
local vegetation = 20

--                  ** TRAP **
---@type int
local trapMouse = 30

--                  ** ANIMALS **
-- **Type of animal**
---@type string
local type = "mouse"

--- **After how many hour the animal will start to destroy the cage/escape**
---@type int
local strength = 24

--- **item given to the player**
---@type string
local item = "Base.DeadMouse"

--- **Hour this animal will be out and when you can catch it**
---@type int
local minHour = 0

--- **Hour this animal will be out and when you can catch it**
---@type int
local maxHour = 0

--- **Min and max "size" (understand hunger reduction) of the animal**
---@type int
local minSizePrey = 1

--- **Min and max "size" (understand hunger reduction) of the animal**
---@type int
local maxSizePrey = 10

--- ---------------------- Start Set Multiplier -------------------

--- **Set Bait Multiplier**
---@param multiplierPrey int
local function setBaitMultiplier(multiplierPrey)
    if not dataValidator.isNumber(multiplierPrey) then
        errHandler.errMsg("Mouse - setBaitMultiplier(multiplierPrey)",
                "multiplierPrey " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    bait.setCheese(cheese * multiplierPrey)
    bait.setChocolate(chocolate * multiplierPrey)
    bait.setPeanutButter(peanutButter * multiplierPrey)
    bait.setProcessedCheese(processedCheese * multiplierPrey)
    bait.setTomato(tomato * multiplierPrey)
end

--- **Set Trap Multiplier**
---@param multiplierPrey int
local function setTrapMultiplier(multiplierPrey)
    if not dataValidator.isNumber(multiplierPrey) then
        errHandler.errMsg("Mouse - setTrapMultiplier(multiplierPrey)",
                "multiplierPrey " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    trap.setTrapMouse(trapMouse * multiplierPrey)
end

--- **Set Zone Multiplier**
---@param multiplierPrey int
local function setZoneMultiplier(multiplierPrey)
    if not dataValidator.isNumber(multiplierPrey) then
        errHandler.errMsg("Mouse - setZoneMultiplier(multiplierPrey)",
                "multiplierPrey " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    zone.setDeepForest(deepForest * multiplierPrey)
    zone.setFarmLand(farmLand * multiplierPrey)
    zone.setForest(forest * multiplierPrey)
    zone.setTownZone(townZone * multiplierPrey)
    zone.setTrailerPark(trailerPark * multiplierPrey)
    zone.setVegetation(vegetation * multiplierPrey)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplierPreySize int
local function setSizeAnimalMultiplier(multiplierPreySize)
    if not dataValidator.isNumber(multiplierPreySize) then
        errHandler.errMsg("Mouse - setSizeAnimalMultiplier(multiplierPreySize)",
                "multiplierPreySize " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    mouse.minSize = minSizePrey * multiplierPreySize;
    mouse.maxSize = maxSizePrey * multiplierPreySize;
end

--- ---------------------- Start init Bait -------------------

--- **Init Bait**
local function initBait()
    creatureFactory.createBait(mouse, bait.bait.CHEESE, bait.getCheese())
    creatureFactory.createBait(mouse, bait.bait.CHOCOLATE, bait.getChocolate())
    creatureFactory.createBait(mouse, bait.bait.PEANUT_BUTTER, bait.getPeanutButter())
    creatureFactory.createBait(mouse, bait.bait.PROCESSED_CHEESE, bait.getProcessedCheese())
    creatureFactory.createBait(mouse, bait.bait.TOMATO, bait.getTomato())
end

--- **Init Trap**
local function initTrap()
    creatureFactory.createTrap(mouse, trap.trap.MOUSE, trap.getTrapMouse())
end

--- **Init Zone**
local function initZone()
    creatureFactory.createZone(mouse, zone.zone.DEEP_FOREST, zone.getDeepForest())
    creatureFactory.createZone(mouse, zone.zone.FOREST, zone.getForest())
    creatureFactory.createZone(mouse, zone.zone.TOWN_ZONE, zone.getTownZone())
    creatureFactory.createZone(mouse, zone.zone.TRAILER_PARK, zone.getTrailerPark())
    creatureFactory.createZone(mouse, zone.zone.VEGETATION, zone.getVegetation())
end

--- **Init**
local function init()
    ---@type int
    local multiplierPrey = SandboxVars.TrappingSurvival.Mouse

    ---@type int
    local multiplierPreySize = SandboxVars.TrappingSurvival.MouseSize

    if not dataValidator.isNumber(multiplierPrey) then
        errHandler.errMsg("Mouse - init()",
                "multiplierPrey " .. errHandler.err.IS_NOT_INT)
        return nil
    elseif not dataValidator.isInt(multiplierPreySize) then
        errHandler.errMsg("Mouse - init()",
                "multiplierPreySize " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    mouse = creatureFactory.creature(type, strength, item, minSizePrey, maxSizePrey, minHour, maxHour)

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplierPrey)
    setTrapMultiplier(multiplierPrey)
    setZoneMultiplier(multiplierPrey)
    setSizeAnimalMultiplier(multiplierPreySize)

    --                  ** Init bait/trap/zone **
    initBait()
    initTrap()
    initZone()

end

---**Get Mouse**
---@return table Mouse
function getMouse()
    init()
    return mouse
end
