---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by lele.
--- DateTime: 13/08/23 23:14
---

-- https://pzwiki.net/wiki/Trapping
-- SteamLibrary/steamapps/common/ProjectZomboid/projectzomboid/media/lua/server/Traps/TrapDefinition.lua

---@class Squirrel

--- ---------------------- Start Squirrel Default values -------------------------------

local creatureFactory = require("CreatureFactory")
local dataValidator = require("lib/DataValidator")
local errHandler = require("lib/ErrHandler")

--- **This is a class**
local Squirrel = {}

--- **This is an animal with its properties**
-- @type table
local squirrel = {}

local bait = require("Bait_TS")
local trap = require("Trap_TS")
local zone = require("Zone_TS")

--                  ** BAIT **
---@type int
local apple = 40
---@type int
local bellPepper = 30
---@type int
local cereal = 45
---@type int
local corn = 40
---@type int
local orange = 40
---@type int
local lettuce = 40
---@type int
local peach = 35
---@type int
local peanutButter = 45
---@type int
local peanuts = 40
---@type int
local popcorn = 40

--                  ** ZONE **
---@type int
local deepForest = 15
---@type int
local forest = 12
---@type int
local townZone = 2
---@type int
local trailerPark = 2
---@type int
local vegetation = 10

--                  ** TRAP **
---@type int
local trapBox = 25
---@type int
local trapCage = 40
---@type int
local trapCrate = 30
---@type int
local trapSnare = 30

--                  ** ANIMALS **
--- **Type of animal**
---@type string
local type = "squirrel"

--- **After how many hour the animal will start to destroy the cage/escape**
---@type int
local strength = 24

--- **Item given to the player**
---@type string
local item = "Base.DeadSquirrel"

--- **Hour this animal will be out and when you can catch it**
---@type int
local minHour = 18
--- **Hour this animal will be out and when you can catch it**
---@type int
local maxHour = 8

--- **Min and max "size" (understand hunger reduction) of the animal**
---@type int
local minSizePrey = 30

--- **Min and max "size" (understand hunger reduction) of the animal**
---@type int
local maxSizePrey = 100

--- ---------------------- Set Multiplier -------------------

--- **Set Bait Multiplier**
---@param multiplierPrey int
local function setBaitMultiplier(multiplierPrey)
    if not dataValidator.isNumber(multiplierPrey) then
        errHandler.errMsg("Squirrel - setBaitMultiplier(multiplierPrey)",
                "multiplierPrey " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    bait.setApple(apple * multiplierPrey)
    bait.setBellPepper(bellPepper * multiplierPrey)
    bait.setCereal(cereal * multiplierPrey)
    bait.setCorn(corn * multiplierPrey)
    bait.setOrange(orange * multiplierPrey)
    bait.setLettuce(lettuce * multiplierPrey)
    bait.setPeach(peach * multiplierPrey)
    bait.setPeanutButter(peanutButter * multiplierPrey)
    bait.setPeanuts(peanuts * multiplierPrey)
    bait.setPopcorn(popcorn * multiplierPrey)
end

--- **Set Trap Multiplier**
---@param multiplierPrey int
local function setTrapMultiplier(multiplierPrey)
    if not dataValidator.isNumber(multiplierPrey) then
        errHandler.errMsg("Squirrel - setTrapMultiplier(multiplierPrey)",
                "multiplierPrey " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    trap.setTrapBox(trapBox * multiplierPrey)
    trap.setTrapCage(trapCage * multiplierPrey)
    trap.setTrapCrate(trapCrate * multiplierPrey)
    trap.setTrapSnare(trapSnare * multiplierPrey)
end

--- **Set Zone Multiplier**
---@param multiplierPrey int
local function setZoneMultiplier(multiplierPrey)
    if not dataValidator.isNumber(multiplierPrey) then
        errHandler.errMsg("Squirrel - setZoneMultiplier(multiplierPrey)",
                "multiplierPrey " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    zone.setDeepForest( deepForest * multiplierPrey)
    zone.setForest(forest * multiplierPrey)
    zone.setTownZone(townZone * multiplierPrey)
    zone.setTrailerPark(trailerPark * multiplierPrey)
    zone.setVegetation(vegetation * multiplierPrey)
end

--- **Set "size" Multiplier**
--- Min and max "size" (understand hunger reduction) of the animal
---@param multiplierPreySize int
local function setMultiplierPreySize(multiplierPreySize)
    if not  dataValidator.isNumber(multiplierPreySize) then
        errHandler.errMsg("Squirrel - setMultiplierPreySize(multiplierPreySize)",
                "multiplierPreySize " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    squirrel.minSize = minSizePrey * multiplierPreySize;
    squirrel.maxSize = maxSizePrey * multiplierPreySize;
end

--- ---------------------- Start init Bait -------------------

--- **Init Bait**
local function initBait()
    creatureFactory.createBait(squirrel.baits, bait.bait.APPLE, bait.getApple())
    creatureFactory.createBait(squirrel.baits, bait.bait.BELL_PEPPER, bait.getBellPepper())
    creatureFactory.createBait(squirrel.baits, bait.bait.CEREAL, bait.getCereal())
    creatureFactory.createBait(squirrel.baits, bait.bait.CORN, bait.getCorn())
    creatureFactory.createBait(squirrel.baits, bait.bait.ORANGE, bait.getOrange())
    creatureFactory.createBait(squirrel.baits, bait.bait.LETTUCE, bait.getLettuce())
    creatureFactory.createBait(squirrel.baits, bait.bait.PEACH, bait.getPeach())
    creatureFactory.createBait(squirrel.baits, bait.bait.PEANUT_BUTTER, bait.getPeanutButter())
    creatureFactory.createBait(squirrel.baits, bait.bait.PEANUTS, bait.getPeanuts())
    creatureFactory.createBait(squirrel.baits, bait.bait.POPCORN, bait.getPopcorn())
end

--- **Init Trap**
local function initTrap()
    creatureFactory.createTrap(squirrel.traps, trap.trap.BOX, trap.getTrapBox())
    creatureFactory.createTrap(squirrel.traps, trap.trap.CAGE, trap.getTrapCage())
    creatureFactory.createTrap(squirrel.traps, trap.trap.CRATE, trap.getTrapCrate())
    creatureFactory.createTrap(squirrel.traps, trap.trap.SNARE, trap.getTrapSnare())
end

--- **Init Zone**
local function initZone()
    creatureFactory.createZone(squirrel.zone, zone.zone.DEEP_FOREST, zone.getDeepForest())
    creatureFactory.createZone(squirrel.zone, zone.zone.FOREST, zone.getForest())
    creatureFactory.createZone(squirrel.zone, zone.zone.TOWN_ZONE, zone.getTownZone())
    creatureFactory.createZone(squirrel.zone, zone.zone.TRAILER_PARK, zone.getTrailerPark())
    creatureFactory.createZone(squirrel.zone, zone.zone.VEGETATION, zone.getVegetation())
end

--- **Init**
local function init()
    ---@type int
    local multiplierPrey = SandboxVars.TrappingSurvival.Squirrel
    ---@type int
    local multiplierPreySize = SandboxVars.TrappingSurvival.SquirrelSize

    if not dataValidator.isNumber(multiplierPrey) then
        errHandler.errMsg("Squirrel - init()",
                "multiplierPrey " .. errHandler.err.IS_NOT_INT)
        return nil
    elseif not dataValidator.isNumber(multiplierPreySize) then
        errHandler.errMsg("Squirrel - init()",
                "multiplierPreySize " .. errHandler.err.IS_NOT_INT)
        return nil
    end

    squirrel = creatureFactory.creature(type, strength, item, minSizePrey, maxSizePrey, minHour, maxHour)

    --                  ** MULTIPLIER **
    setBaitMultiplier(multiplierPrey)
    setTrapMultiplier(multiplierPrey)
    setZoneMultiplier(multiplierPrey)
    setMultiplierPreySize(multiplierPreySize)

    --                  ** Init bait/trap/zone **
    initBait()
    initTrap()
    initZone()
end

---**Get Squirrel**
---@return table Squirrel
function Squirrel.getSquirrel()
    init()
    return squirrel
end

return Squirrel